apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deploy Python Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    steps:
    - name: Checkout Repository
      uses: cloudbees-io/checkout@v1
      
      
    - name: Setup AWS CLI
      uses: cloudbees-io/configure-aws-credentials@v1
      id: aws-login
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.ss_aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.ss_aws_secret_access_key_id }}
    
    - name: Check Changed Files
      uses: docker://alpine/git:latest
      run: |
        echo "List of changed files:" 
        echo $(git diff --name-only HEAD^ HEAD)
    
    

