apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deploy Python Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    steps:
    - name: Checkout Repository
      uses: cloudbees-io/checkout@v1

    - name: Setup AWS CLI
      uses: cloudbees-io/configure-aws-credentials@v1
      id: aws-login
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.ss_aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.ss_aws_secret_access_key }}
    
    - name: Check Changed Files
      uses: docker://alpine/git:latest
      run: |
        echo "List of changed files:" 
        echo $(git show --name-only --oneline HEAD)

    - name: Download from Amazon S3
      uses: cloudbees-io/s3-download-object@v1
      with:
          file-path: "lambda-deployment.zip"
          bucket-name: "lambda-func-deployment"
          s3-path: "lambda-deployment-5d0b4dc7-13ae-43a1-81ba-d5a2372248ba.zip" 

    - name: Unzip and copy modified files 
      uses: docker://ubuntu:latest
      shell: sh
      run: |
          apt-get update && apt-get install -y git
          apt-get install unzip
          apt-get install zip
          unzip lambda-deployment.zip -d lambda_env

          for file in $(git show --name-only --oneline HEAD |tail -n +2 | grep '\.py$')
            do 
              if [[ "$file" == *.py ]]
                then
                  mkdir -p lambda_env/$(dirname $file)
                  cp $file lambda_env/$file
                  # Print what you've done with the file
                  echo "Copied $file to lambda_env/$file"
                  echo "Content of $file after copying:"
                  cat lambda_env/$file
              fi
            done
          

          cd lambda_env
          zip -r ../updated_lambda.zip .
          cd ..

        # Copy only the modified .py files from the commit into the unzipped directory
        # This will maintain their directory structure.


    - name: Upload the modified zip to S3
      uses: cloudbees-io/s3-upload-object@v1
      with:
        file-path: "updated_lambda.zip"
        bucket-name: "lambda-func-deployment"
        s3-path: "lamdba_deployment_new.zip"
    
          
         

    
    

